version = 0.1

[default.deploy.parameters]
stack_name = "ayah-mailer"
resolve_s3 = true
s3_prefix = "ayah-mailer"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AppSecretsId=\"ayah-mailer/config\" MailFrom=\"hello@realharis.works\" HttpApiUrl=\"\" QuranApiOauthUrl=\"https://oauth2.quran.foundation\" OtpTtlMinutes=\"10\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
